[project]
name = "course-0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "backtrader>=1.9.78.123",
    "pandas>=2.2.3",
    "torch>=2.6.0",
    "transformers>=4.51.2",
]
